apiVersion: v1
kind: Service
metadata:
  name: go-infoapp-frontend
spec:
  type: ClusterIP
  selector:
    app: infoapp
    tier: frontend
    env: base
  ports:
  - port: 8080
    targetPort: frontend
