apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-infoapp-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      $setElementOrder/containers:
      - name: frontend
      containers:
      - $setElementOrder/env:
        - name: VERSION
        env:
        - name: VERSION
          value: production
        image: evillgenius/infoapp-fe:v1
        name: frontend