apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-infoapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      $setElementOrder/containers:
      - name: backend
      containers:
      - $setElementOrder/env:
        - name: VERSION
        env:
        - name: VERSION
          value: production
        image: evillgenius/infoapp-be:v1
        name: backend
